# Generated by Django 2.0.1 on 2018-02-02 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='default', max_length=100, verbose_name='发送者用户标识')),
                ('letter', models.CharField(max_length=600, verbose_name='信件内容')),
                ('status', models.CharField(choices=[(1, 'seccues'), (2, 'failed')], default=1, max_length=10, verbose_name='信件状态')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='信件发送时间')),
                ('to_user_id', models.CharField(default='default', max_length=100, verbose_name='收信者用户标识')),
                ('record_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='微信昵称')),
                ('openid', models.CharField(default='default', max_length=100, verbose_name='用户标识')),
                ('cookie', models.CharField(default='', max_length=100, verbose_name='用户认证标识')),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女'), (0, '未知')], max_length=10, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
